-- Script was generated by Devart dbForge Studio Express for MySQL, Version 5.0.40.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 4/3/2012 4:38:25 PM
-- Server version: 5.5.8
-- Client version: 4.1

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';


--
-- Definition for table entry
--
DROP TABLE IF EXISTS entry;
CREATE TABLE entry (
  id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  url_key VARCHAR(50) NOT NULL,
  parent_id INT(11) UNSIGNED DEFAULT NULL,
  title VARCHAR(255) NOT NULL,
  content TEXT DEFAULT NULL,
  active TINYINT(4) DEFAULT 1,
  default_home TINYINT(4) DEFAULT 0,
  created_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `index` TINYINT(4) UNSIGNED DEFAULT 0,
  last_updated_time DATETIME DEFAULT NULL,
  PRIMARY KEY (id),
  INDEX FK_entry__entry_id (parent_id),
  UNIQUE INDEX url_key (url_key),
  CONSTRAINT FK_entry__entry_id FOREIGN KEY (parent_id)
    REFERENCES entry(id) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;